const data = {
    products: [
      {
        _id: '1',
        name: 'eyelashes',
        category: 'beauty',
        image: '/images/img1.jpeg',
        price: 12,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'braided wig',
        category: 'beauty',
        image: '/images/img1.jpeg',
        price: 10,
        countInStock: 0,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'body lotion',
        category: 'beauty',
        image: '/images/img1.jpeg',
        price: 12,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 5,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'scarf',
        category: 'beauty',
        image: '/images/img1.jpeg',
        price: 2,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 11,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'powder',
        category: 'beauty',
        image: '/images/img1.jpeg',
        price: 12,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 16,
        description: 'high quality product',
      }
    ],
  };
  export default data;